language: java

dist: trusty

jdk: openjdk11
addons:
  apt:
    packages:
    - junit

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"
  - javac -classpath /usr/share/java/junit.jar PriorityQueueTest.java
  - java -classpath .:/usr/share/java/junit.jar PriorityQueueTest
  # - make clean
  # - make run