language: java

addons:
  apt:
    packages:
    - junit

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"
  - make clean
  - make run