language: java

dist: trusty

addons:
  apt:
    packages:
    - junit5

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"
  - make clean
  - make complie
  - make run