language: java

dist: trusty

jdk: openjdk11
addons:
  apt:
    packages:
    - junit

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)